Repository Data-Flower/ETL_Pipeline, pull requests merged in 2023-04, with the labels that each got.

#4 SG_test request
  Work_JH/testcode1.py
  Work_SG/init.txt
Labels: test

#5 Update/core modules
  README.md
  Work_JH/test/bz_A.bz2
  Work_JH/test/convert_texts/byte_A.txt
  Work_JH/test/convert_texts/byte_AB.txt
  Work_JH/test/convert_texts/byte_A가.txt
  Work_JH/test/convert_texts/byte_가.txt
  Work_JH/test/convert_texts/empty.txt
  Work_JH/test/convert_texts/txt_A.txt
  Work_JH/test/convert_texts/txt_AB.txt
  Work_JH/test/convert_texts/txt_A가.txt
  Work_JH/test/convert_texts/txt_가.txt
  Work_JH/test/lz_A.lzma
  Work_JH/test/zip_A
  Work_JH/test/zip_A.txt
  Work_JH/test/zip_A.zip
  Work_JH/test/zip_A2.gz
  Work_JH/test/zip_A2.tar
  Work_JH/test/zip_A2.zip
  Work_JH/test/zip_A3.zip
  Work_JH/test_compress.py
  doc/LOG.md
  examples/todo_example.txt
  modules/compress_/__init__.py
  modules/converts_/__init__.py
  modules/cryptography_/__init__.py
  modules/json_/__init__.py
  modules/requests_/__init__.py
  modules/times_/__init__.py
Labels: enhancement

#6 Update/core modules: v0.2 compress_ 코어 모듈 업데이트 진행
  Work_JH/init.txt
  Work_JH/test.py
  Work_JH/test_compress2.py
  module_test.py
  modules/__init__.py
  modules/compress_/__init__.py
  modules/compress_/gzip_.py
  modules/compress_/lzma_.py
  modules/compress_/zlib_.py
Labels: documentation, enhancement

#7 Update/core modules: v0.2 플랫폼 코어 보강작업 수행
  main.py
  modules/aws_/__init__.py
  modules/compress_/__init__.py
  modules/cryptography_/__init__.py
  modules/json_/__init__.py
  modules/requests_/__init__.py
  modules/times_/__init__.py
Labels: documentation, enhancement

#8 Update/core modules: v0.2.1 압축모듈 함수 파라미터 추가
  modules/compress_/__init__.py
  modules/compress_/gzip_.py
  modules/compress_/lzma_.py
  modules/compress_/zlib_.py
Labels: enhancement
